### ISSUE TITLE
Add ssl support for the marketing site 

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contentacms.github.io#3]

**Comment by e0ipso** [comment]
https://contentacms.org does not work

**Comment by dawehner** [comment]
I wonder whether @justafish can help you there

**Comment by mattgrill** [comment]
@e0ipso It doesn't appear that you can use the github-provided ssl with a custom domain. We could move the site to something like [now.sh](https://zeit.co/now), or use something like cloudflare. I'm happy to set either of those up.

**Comment by e0ipso** [comment]
Given that:
> It doesn't appear that you can use the github-provided ssl with a custom domain.

I'm closing this issue.
